name: Cloud189Checkin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 2,14 * * *

jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        cd src/python/189checkin
        pip3 install -r requirements.txt
        
    - name: Checkin
      run: |
        user='${{ secrets.USER_189 }}'
        pwd='${{ secrets.PWD_189 }}'
        python3 checkin.py --username ${user} --password ${pwd}