name: deno fmt and lint and fetch
on: 
  push:
  schedule:
    - cron: '0 8 * * *'
jobs:
  fectch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Deno
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.x
      - name: Check formatting
        run: deno fmt 

      - name: Run main.js
        run: deno run -A src/deno/main.js
      - name: Run convert.js
        run: deno run -A src/deno/convert.js
      - run: |
          git config --global user.email sunclx@gmail.com
          git config --global user.name sunclx
          git add .
          git commit -m "deno fmt auto" -a       
      - run: git push
